[project]
name = 'pyne'
version = '0.0.1'
description = 'Python library for low level graphics control'
readme = 'README.md'
requires-python = '>=3.8'
license = { file = 'LICENSE.txt' }

[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']
