class Window:
	def __init__(self, title: str, width: int, height: int, flags: int = 0): ...
	
	@property
	def size(self) -> tuple[int, int]: ...
	@size.setter
	def size(self, s: tuple[int, int]): ...
	
	@property
	def title(self) -> str: ...
	@title.setter
	def title(self, s: str): ...
