from typing import Callable

class Image:
	def __init__(self, path: str) -> None: ...

	def get_size(self) -> tuple[int, int]: ...

class Window:
	def __init__(self, title: str, width: int, height: int, flags: int = 0): ...
	
	@property
	def size(self) -> tuple[int, int]: ...
	@size.setter
	def size(self, s: tuple[int, int]): ...
	
	@property
	def title(self) -> str: ...
	@title.setter
	def title(self, s: str): ...

	def fill(self, r: int, g: int, b: int, a: int = 255): ...
	def update(self): ...

	def render(image: Image, pos: tuple[int, int]): ...

def attach_handler(event_id: int, func: Callable): ...
def update(): ...

def _get_handlers() -> dict[int, Callable]: ...